version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: offboarding_postgres
    ports:
      - "5421:5432"
    environment:
      POSTGRES_DB: new_employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - offboarding_network

  backend:
    build: ./Backend
    container_name: offboarding_backend
    ports:
      - "3421:3421"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: new_employee_db
      DB_PASSWORD: admin234
      DB_PORT: 5432
    networks:
      - offboarding_network

  frontend:
    build: ./Frontend
    container_name: offboarding_frontend
    ports:
      - "8041:80"
    networks:
      - offboarding_network

  hr_page:
    build: ./Hr_page
    container_name: offboarding_hr_page
    ports:
      - "8042:80"
    networks:
      - offboarding_network

volumes:
  pgdata:

networks:
  offboarding_network:

